version: "3.7"
services:
    php74:
        build:
            context: docker
            dockerfile: php74.dockerfile
        working_dir: /var/app
        entrypoint: composer
        volumes:
            - .:/var/app

    php81:
        build:
            context: docker
            dockerfile: php81.dockerfile
        working_dir: /var/app
        entrypoint: composer
        volumes:
            - .:/var/app
