version: "3.7"
services:
    php71:
        build:
            context: docker
            dockerfile: php71.dockerfile
        working_dir: /var/app
        entrypoint: composer
        volumes:
            - .:/var/app

    php74:
        build:
            context: docker
            dockerfile: php74.dockerfile
        working_dir: /var/app
        entrypoint: composer
        volumes:
            - .:/var/app
